# Generated by Django 2.2.6 on 2019-11-19 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_aggregator', '0002_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
